### PR TITLE
[WIP] testing branch

### PR DESCRIPTION
**Pull request by askl56**
Don't pull yet, this is a work in progress. Adding testing.

### CODE REVIEW

**Comment by askl56** [comment]
Hey, I just found all the minitest test tests.. What's the plan with this? You can merge what i've done so far since it's in essence regression testing of the models.

**Comment by phezco** [comment]
Re: the plan with the minitest tests -- let's work on migrating them over to rspec tests.  Once you have a few controller specs implemented (even just some light basic specs), I can work on that.

**Comment by askl56** [comment]
Are you waiting to merge until then?

**Comment by phezco** [comment]
Nope, all merged.

**Pull request merged**
