### PR TITLE
cleaning up code

### PR DESCRIPTION
**Pull request by askl56**

### CODE REVIEW

**Comment by askl56** [comment]
I'll keep pushing to this branch, I've been meaning to do more but I'll start properly once work calms down.

**Comment by phezco** [comment]
Hey @askl56 - cool, thanks for the commits! Did you do a lot of this using Rubocop?

One problem I've found though is that the && syntax instead of 'and' causes problems. Not sure if it's my local setup or what, but I'd prefer we stick with the 'and' syntax instead of && return.

Can you roll back the && changes?

**Comment by askl56** [comment]
I've just done a regex for "and" and can't find where you're referring to? It is early in the morning, so it might be me.

**Comment by phezco** [comment]
Like your change in admin_controller.rb:

```
      render action: :transactions,
-        alert: "Could not find user with username: #{params[:username]}" and return
+      render(action: :transactions,
+             alert: "Could not find user with username: #{params[:username]}") && return
```

For some reason the && return syntax causes things to break in my setup.

**Comment by askl56** [comment]
Ah ok. I will fix now.

**Comment by askl56** [comment]
I've unfixed the `&&` syntax. The next thing I was going to do was start moving logic from views to helpers.

**Pull request merged**
