### PR TITLE
Here's my attempt on fixing most of the formatting issues by rubocop

### PR DESCRIPTION
**Pull request by voyera**

### CODE REVIEW

**Comment by phezco** [comment]
I bumped into some issues with the changes rubocop suggested to switch 'and return' to '&& return'. I rolled those back to 'and return'.

Also had to rip out some format.html, json responders that weren't being used anyway.

**Comment by voyera** [comment]
Ah, that makes sense. I also noticed a lot of format.html, json would never get reached but  I didn't want to alter those while only making cosmetic changes so I left them as is :)

**Comment by phezco** [comment]
Thanks for the PR!  Have you signed up at Phez.co?

I'd be happy to tip you a few mbtc this month for contributing to Phez via your rubocop PR.

**Comment by voyera** [comment]
Thanks! My username is voyera :)

**Comment by phezco** [comment]
Cool. I just credited you with 25 mbtc on Phez.co (go to My Account -> Transactions).  Payments go out at the end of the month. I know it isn't much but I really appreciate your help. If you have any questions about the codebase, just let me know!

**Pull request merged**
