### PR TITLE
BD - random_subphez - Added random subphez link feature. DRYed sideba…

### PR DESCRIPTION
**Pull request by brian-davis**
…r view links. Added controller test (minitest).  Added fixture data, skipped tests with errors. Syntax changes for indentation, line length, trailing whitespace, Ruby 1.9 hash syntax

Phez looks good.  It was interesting to see a Reddit clone in Rails.  The Bitcoin integration is a good idea.  I noticed it was missing a random subphez link, which is IMO a crucial feature, so I went ahead and added it, and added a test.  There was an error in the one test already there when I ran `rake test`, something with authentication and fixtures.  I skipped the tests rather than trying to dig into the code  to resolve that issue, but did add some basic fixtures.

### CODE REVIEW

**Comment by phezco** [comment]
Hey @brian-davis - Thanks for your work on this!

The only thing I prefer is using FactoryGirl over fixtures, so I went ahead and implemented that. Also went through and implemented the post controller minitests.

See my changes + the PR into master here: https://github.com/phezco/phez/pull/13

Thanks again!

ps. If you want, create an account on Phez.co and I'll send you an mbtc tip for your efforts.

**Comment by phezco** [comment]
Not sure if you're interested in contributing more to Phez. If you are, let me know and I can invite you to the Slack channel.

**Comment by brian-davis** [comment]
I signed up as 'gigantopithecus', and my bitcoin donation key is apparently 1HYGSg18GDTJ8vBrTFDu15UP9eah1ysiNW.

Actually, just noticed there is a reddit/u/gigantopithecus already.  Maybe it is bad form to use that name?  Like if you're encouraging Redditors to switch over.  I could choose something else no problem.

I'd be happy to contribute more to Phez.

**Comment by phezco** [comment]
Cool. I credited your account with an 15 mbtc tip. Payments go out at the end of the month.

Re: the reddit user, it's up to you. I'd stick with 'gigantopithecus' for now since I just credited that account with a btc transaction.

ps. I invited you to the Phez Development Slack channel.

**Pull request merged**
